# -*- coding: utf-8 -*-
"""v1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14c4lPid_eMWKdwxbkAMlUhmyna1tnHiY
"""



a=5
b=7
c=6
x=7
y=a*x*x+b*x+c
print(y)